---
- name: Install MySQL
  tags: mysql
  package:
    name: "{{ mysql_modules }}"
    state: latest
    update_cache: yes

- name: Start and Enable MySQL service
  tags: mysql
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: [ mysql, mysql-root ]

- name: Remove all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]

- name: Remove the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]

- name: Creates database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]

- name: Create backup directory
  tags: [ mysql, backup ]
  file:
    path: /home/ubuntu/backups
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Add daily backup cron job
  tags: [ mysql, backup, cron ]
  cron:
    name: "MySQL Backup"
    minute: '0'
    hour: '1'
    job: "sudo mysqldump -u root -p'{{ mysql_root_password }}' --all-databases > /home/ubuntu/backups/mysql-$(date +%Y%m%d).sql"
    user: ubuntu
